name: Airflow DAGS test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose build
      - name: docker-compose up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose up -d
      - name: Check running containers
        run: docker-compose ps -a
      - name: Check logs
        run: docker-compose logs app
      - name: Test with pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec build_airflow-worker_1 pytest
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down