name: CI Workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker-compose-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        working-directory: ./build
        run: docker-compose build
      - name: docker-compose up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        working-directory: ./build
        run: docker-compose up -d
      - name: Check running containers
        working-directory: ./build
        run: docker-compose ps -a
      - name: Check logs
        working-directory: ./build
        run: docker-compose logs airflow-worker
      - name: Stop containers
        if: always()
        working-directory: ./build
        run: docker-compose down
  python_test_with_flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip check
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 --ignore E501 build --benchmark -v
    - name: Test with Pytest
      run: |
        pip install pytest
        cd tests || exit
        pytest ./ -v