  name: Change of docker-compose.yml
  on:
    push:
      branches: [ main ]

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Tests
          uses: cloudposse/github-action-docker-compose-test-run@main
          with:
            registry: docker.pkg.github.com
            workdir: ./build/
            file: docker-compose.yaml
            service: airflow-webserver
            command: echo 1